collections:
  dynasties:
    output: true
collections:
  figures:
    output: true

    
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"